
name: Singularity Matrix Build

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.def'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: def-files
    strategy:
      matrix:
        def-file: ${{ fromJson(needs.def-files.outputs.files) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0

    - name: Build the singularity container
      run: |
        singularity build container.sif ${{ matrix.def-file }}

    - name: Login to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

    - name: Push Container to Registry
      run: |
        repo=${{ github.repository }}
        repo=`echo "${repo,,}"`
        
        # Extract the directory and filename (without extension) from the .def path
        dir_name=$(dirname "${{ matrix.def-file }}")
        dir_name=${dir_name#./}  # Remove leading './' if present
        file_name=$(basename "${{ matrix.def-file }}" .def)
        
        # Construct the full image path as repo/subdirectory:filename
        singularity push container.sif oras://ghcr.io/${repo}/${dir_name}:${file_name}

  def-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list-defs.outputs.def-files }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - id: list-defs
      run: |
        # Find only the .def files that have been modified in the latest push
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.def')
        if [ -z "$files" ]; then
          echo "No .def files changed."
          echo "::set-output name=def-files::[]"
        else
          files=$(echo "$files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "::set-output name=def-files::$files"
        fi